/**
 * Generated from src/v6/external-api/api.json and src/v6/source.json.
 * Do not edit this file directly. Run npm run generate:dts instead.
 */
export interface TallyClientOptions {
    /** Tally HTTP endpoint. Defaults to http://localhost:9000. */
    url?: string;
    /** HTTP method used for the Tally request. Defaults to POST. */
    method?: string;
    /** Additional request headers. */
    headers?: Record<string, string>;
    /** Abort the request after this many milliseconds. */
    timeout?: number;
    /** Optional fetch-compatible implementation for tests or adapters. */
    fetch?: (url: string, options: {
        method: string;
        headers: Record<string, string>;
        body: string;
        signal?: unknown;
    }) => Promise<{
        ok: boolean;
        status: number;
        text: () => Promise<string>;
    }>;
}

export type TallyApi = {
    masters: {
        units: {
            /** Runs tally.masters.units.fetch and returns Tally's raw XML response. */
            fetch: (company: string) => Promise<string>;
        };
        stockItems: {
            /** Runs tally.masters.stockItems.withBatches and returns Tally's raw XML response. */
            withBatches: (company: string) => Promise<string>;
        };
        ledgers: {
            /** Runs tally.masters.ledgers.withGstDetails and returns Tally's raw XML response. */
            withGstDetails: (company: string) => Promise<string>;
        };
        stockGroup: {
            /** Runs tally.masters.stockGroup.withParent and returns Tally's raw XML response. */
            withParent: (company: string) => Promise<string>;
        };
    };
};

/** Create an independently configured Tally client. */
export declare const createTallyClient: (options?: TallyClientOptions) => TallyApi;

/** Default Tally client using the package connection defaults. */
export declare const tally: TallyApi;

export default tally;
