/**
 * Generated from tally-spec/api.json and tally-spec/source.json.
 * Do not edit this file directly. Run npm run generate:dts instead.
 */
export interface TallyClientOptions {
    /** Tally HTTP endpoint. Defaults to http://localhost:9000. */
    url?: string;
    /** HTTP method used for the Tally request. Defaults to POST. */
    method?: string;
    /** Additional request headers. */
    headers?: Record<string, string>;
    /** Abort the request after this many milliseconds. */
    timeout?: number;
    /** Optional fetch-compatible implementation for tests or adapters. */
    fetch?: (url: string, options: {
        method: string;
        headers: Record<string, string>;
        body: string;
        signal?: unknown;
    }) => Promise<{
        ok: boolean;
        status: number;
        text: () => Promise<string>;
    }>;
}

export type TallyApi = {
    company: {
        /** Runs tally.company.fetch and returns Tally's raw XML response. */
        fetch: (company: string) => Promise<string>;
    };
    vouchers: {
        purchases: {
            /** Runs tally.vouchers.purchases.fetch and returns Tally's raw XML response. */
            fetch: (company: string) => Promise<string>;
        };
        sales: {
            /** Runs tally.vouchers.sales.fetch and returns Tally's raw XML response. */
            fetch: (company: string) => Promise<string>;
        };
    };
    masters: {
        unit: {
            /** Runs tally.masters.unit.all and returns Tally's raw XML response. */
            all: (company: string) => Promise<string>;
        };
        units: {
            /** Runs tally.masters.units.fetch and returns Tally's raw XML response. */
            fetch: (company: string) => Promise<string>;
            /** Runs tally.masters.units.all and returns Tally's raw XML response. */
            all: (company: string) => Promise<string>;
        };
        stockItem: {
            /** Runs tally.masters.stockItem.all and returns Tally's raw XML response. */
            all: (company: string) => Promise<string>;
            /** Runs tally.masters.stockItem.withBaseUnits and returns Tally's raw XML response. */
            withBaseUnits: (company: string) => Promise<string>;
            /** Runs tally.masters.stockItem.withBatches and returns Tally's raw XML response. */
            withBatches: (company: string) => Promise<string>;
        };
        stockItems: {
            /** Runs tally.masters.stockItems.withBatches and returns Tally's raw XML response. */
            withBatches: (company: string) => Promise<string>;
        };
        ledger: {
            /** Runs tally.masters.ledger.all and returns Tally's raw XML response. */
            all: (company: string) => Promise<string>;
            /** Runs tally.masters.ledger.withDetails and returns Tally's raw XML response. */
            withDetails: (company: string) => Promise<string>;
            /** Runs tally.masters.ledger.withGstDetails and returns Tally's raw XML response. */
            withGstDetails: (company: string) => Promise<string>;
        };
        ledgers: {
            /** Runs tally.masters.ledgers.withGstDetails and returns Tally's raw XML response. */
            withGstDetails: (company: string) => Promise<string>;
        };
        stockGroup: {
            /** Runs tally.masters.stockGroup.all and returns Tally's raw XML response. */
            all: (company: string) => Promise<string>;
            /** Runs tally.masters.stockGroup.withParent and returns Tally's raw XML response. */
            withParent: (company: string) => Promise<string>;
        };
        stockGroups: {
            /** Runs tally.masters.stockGroups.withParent and returns Tally's raw XML response. */
            withParent: (company: string) => Promise<string>;
        };
        godown: {
            /** Runs tally.masters.godown.all and returns Tally's raw XML response. */
            all: (company: string) => Promise<string>;
            /** Runs tally.masters.godown.withParent and returns Tally's raw XML response. */
            withParent: (company: string) => Promise<string>;
        };
    };
    reports: {
        stockSummary: {
            /** Runs tally.reports.stockSummary.fetch and returns Tally's raw XML response. */
            fetch: (company: string) => Promise<string>;
        };
    };
};

/** Create an independently configured Tally client. */
export declare const createTallyClient: (options?: TallyClientOptions) => TallyApi;

/** Default Tally client using the package connection defaults. */
export declare const tally: TallyApi;

export default tally;
